### ISSUE TITLE
Systray App Name

### ISSUE THREAD

**Issue by alfalco** [SibrenVasse/deezer#1]
Is it possible to change the application name as it appears in systray?

![Screenshot_20190821_180727](https://user-images.githubusercontent.com/2464186/63468708-e45fa280-c43e-11e9-94f3-d358332e4bcf.png)

**Comment by SibrenVasse** [comment]
I'm sorry, but unfortunately this does not seem possible as tray.setTitle() is not available on Linux.
See electron issue for reference:
https://github.com/electron/electron/issues/4742
