### ISSUE TITLE
default value of desktop notifications

### ISSUE THREAD

**Issue by antoinemadec** [SibrenVasse/deezer#13]
First, thanks for the great app !

I updated Deezer recently (using Majarro) and I had to re-enable the desktop notifications in "App Preferences".
After that, it worked like before : each new song would trigger a notification. Swell !

Here are my questions:

1. did the default value of desktop notifications change recently ?
2. is it intentional to disable the desktop notifications by default ?

**Comment by SibrenVasse** [comment]
Hi! The packaging process for this app mostly just redistributes the code of the windows Deezer desktop app and modifies it slightly to work on Linux.
In this case, the default setting for desktop notifications is not something I modify in any way, so this is a change from Deezer, not me. It's almost impossible for me to see the changes from release to release, as the code of the web app is minified and mostly unreadable.

You could ask them on the forums if you want to.

**Comment by antoinemadec** [comment]
Thanks for the clear explanation 🙂
