### ISSUE TITLE
Media buttons stopped working recently

### ISSUE THREAD

**Issue by zeknoss** [SibrenVasse/deezer#15]
Hi Sibren,
In the most recent update, the media controls are no longer working. The application doesn't even get recognized by the Media Player widget or any other system module that is related to media player functions.
One other thing is, the cover arts used to work before, and they are gone too.
For your information.

Kind regards!

**Comment by SibrenVasse** [comment]
Hi,

Unfortunately my MPRIS (media control) implementation that I patched into this package was the only reason that ever worked. Since upstream 5.x these patches are no longer compatible with the source code from Deezer. Thus far I have not found a way to re-implement these patches.

**Comment by zeknoss** [comment]
Oh, that's a bummer, but I cannot thank you enough for the awesome job you already did so far! Thank you my friend!

**Comment by aunetx** [comment]
Hi @SibrenVasse, I created the https://github.com/aunetx/deezer-linux repository, to package the deezer app for linux (including flatpak, appimage, rpm, deb, snap...). Your repo helped me a lot, and I first would like to thank you!

I noticed the media buttons do not work either with my port: it looked like it worked at first (using 5.30.00) when not using flatpak, but after trying to make flatpak support MPRIS too, nothing works anymore (there are empty MPRIS control, which do not react to anything).

I just contact you here to tell you that if you need help to re-implement MPRIS, I would love to help you ; as it is the only missing feature for me to release a fully-working flatpak app (and maybe push it to flathub).

If you need (and you want) help, you can contact me on discord at `aunetx#2944`.

Thanks for your work,
Aurélien Hamy

**Comment by aunetx** [comment]
Looks like the last update made this work, at least using flatpak from my repo

**Comment by aunetx** [comment]
Yeah, MPRIS buttons now work great! I don't know what did that, I updated to deezer 5.30.100 and used yarn in place of npm to download dependencies and build the electron executable; and now everything works as expected.

If using yarn fixed this problem, I don't know what is possible to do here, except maybe re-build the modules from the archive (using yarn), but this would require heavier repackaging than what you do here, and may be less stable if your users do it at each update (as the dependencies would change dynamically).
