### ISSUE TITLE
Option to disable systray - as in aunetx's Fork

### ISSUE THREAD

**Issue by pschloenzke** [SibrenVasse/deezer#18]
Hey! I am using the [Flatpak version from aunetx](https://github.com/aunetx/deezer-linux) on the basis of your work.
I [asked there](https://github.com/aunetx/deezer-linux/issues/18) about an option to disable the systray functionality, as it can be irritating on environments without a systray like GNOME and personally, I just prefer to not have Deezer in systray :)
This was done through [this patch](https://github.com/aunetx/deezer-linux/commit/a659f55041e4563b4802b7293abcd3ad96b8a59a) which provides `--disable-systray` as a launch option. This works perfectly for me and maybe would also benefit users of your AUR version?

Thanks for your work on Deezer!

**Comment by SibrenVasse** [comment]
Thank you for creating an issue! I have merged the patches from the fork back to this repository. You can try v5.30.230.

There are now two systray related switches:
```
--disable-systray
--start-in-tray
```

**Comment by pschloenzke** [comment]
Great, thank you!
