### ISSUE TITLE
Cannot move song in playlist

### ISSUE THREAD

**Issue by daxid** [SibrenVasse/deezer#2]
When moving a song in a playlist, using drag and drop, the song appear to be moved but cannot be clicked on  its new position. If I exit the playlist and load it again, the song is back in its original position.

**Comment by SibrenVasse** [comment]
If I try this on my machine this works fine. 

On what operating system are you using the app? Are there errors if you run the program on the command line? You can start the app on linux with devtools with 'env DZ_DEVTOOLS=yes deezer'.

**Comment by daxid** [comment]
Word ! You are absolutely right...

I realize it happens only on a specific playlist. It must be on Deezer side...

I'm closing this, sorry for the wrong report !
