### ISSUE TITLE
Discord Rich Presence

### ISSUE THREAD

**Issue by Francehelder** [SibrenVasse/deezer#21]
Please add Discord Rich Presence support.
Something like the Spotify view:

![image](https://user-images.githubusercontent.com/14970431/201454807-d4739ef3-d4ae-439d-afdc-46c8575dc385.png)

**Comment by SibrenVasse** [comment]
Hi, Thank you for creating an issue!

Unfortunately, this is something for Deezer (the company) to implement. You can see the relevant feature request here: https://en.deezercommunity.com/ideas/deezer-discord-rich-presence-7434
