### ISSUE TITLE
Minimize to tray

### ISSUE THREAD

**Issue by zeknoss** [SibrenVasse/deezer#4]
Hello,
The window does not behave as it should regarding minimizing and tray icon feature.
The application shuts down when clicked on close button instead of minimizing to tray icon.
In an ideal world, the application should minimize to tray icon instead of shutting down when clicked on the close button, and when tray icon is double-clicked it should restore the window.

Is it possible to fix?
Thank you very much for your time!

**Comment by SibrenVasse** [comment]
Yeah I see, never noticed that with my tiling window manager.
Can you try the latest 4.18.40-2?

**Comment by zeknoss** [comment]
Hi @SibrenVasse,
The latest version in bauh is 4.18.40-1, how can I upgrade to the said version?

PS: Sorry for the late response!

**Comment by SibrenVasse** [comment]
You can build a package to test with:

```
git clone https://github.com/SibrenVasse/deezer
cd deezer
makepkg -si
sudo pacman -U $tarfile
```

**Comment by zeknoss** [comment]
Hey @SibrenVasse 
Thank you for the info. Now it's working like a charm. The close button sends the application to trey icon. Cheers!
