### ISSUE TITLE
[FR]Add verbose/debug mode

### ISSUE THREAD

**Issue by yurikoles** [SibrenVasse/deezer#6]
According to #5

**Comment by SibrenVasse** [comment]
You can enable the chromium devtools by running:
```
env DZ_DEVTOOLS=yes electron6 /usr/share/deezer/app.asar
```
The verbose mode of the logging facilities provided by Deezer is already enabled. (These are the messages you see on your console)

To debug node, you can extract the source files to a directory and inspect the node process by attaching using the chromium debugging tools:
```
asar extract /usr/share/deezer/app.asar $dest
electron6 --inspect-brk=$port $dest
```
