### ISSUE TITLE
[feature reqest]

### ISSUE THREAD

**Issue by userofryzen** [SibrenVasse/deezer#7]
first, I don't know if it's technically possible. I am not able to do this in code because I am not a developper.
But i have thought that may be it's possible to advice the user of the app that the support of this app is not official and may be they want to vote and comment in the idea of deezer community so we can "make " some noise to get developpers to make a native Linux deezer app.
Something like:
" this package is not official and it's not supported by deezer, may be you cant to vote and comment to give the Linux app some support"
https://en.deezercommunity.com/got-an-idea-50/linux-needs-a-native-client-for-deezer-856
Each time the deezer app is open the message pops up, after this there will be a checkbox that we can uncheck so each startup is not disturbing us. At least we can " publicity" the topic and we "maybe" can get the native Linux official support we merecly.

**Comment by daltroaugusto** [comment]
It seems to be technically possible. I don't know a lot about Electron but I'm a former webdeveloper and, from what I know, it's probably possible to inject some js in the main instance. The big issue would be probably license-related.

**Comment by SibrenVasse** [comment]
Deezer has already replied and said they're actively developing Deezer for Linux. So I don't think it's very helpful to do this.

https://en.deezercommunity.com/ideas/linux-needs-a-native-client-for-deezer-321/index11.html (6th comment from the bottom)
