### ISSUE TITLE
error running install script

### ISSUE THREAD

**Issue by pskraemer11** [SibrenVasse/deezer#8]
Hi,

running the install.sh I get an error message an it stops wating on input:

"npm WARN enoent ENOENT: no such file or directory, open '/home/peter/bin/deezer-mpris/npm_temp/package.json'
npm WARN npm_temp No description
npm WARN npm_temp No repository field.
npm WARN npm_temp No README data
npm WARN npm_temp No license field.
prettier requires at least version 10.13.0 of Node, please upgrade
prettier requires at least version 10.13.0 of Node, please upgrade
can't find file to patch at input line 5
Perhaps you used the wrong -p or --strip option?
The text leading up to this was:
--------------------------
|diff --git a/build/main.js b/build/main.js
|index a229f52..0f1955b 100644
|--- a/build/main.js
|+++ b/build/main.js
--------------------------
File to patch:"

**Comment by SibrenVasse** [comment]
This is a Arch Linux package, forks are not supported by me.
Please contact @siphomateke.

**Comment by siphomateke** [comment]
@pskraemer11 I've copied your issue to the correct repository https://github.com/siphomateke/deezer/issues/1.
